- name: Mise à jour avec APT
  hosts: all
  become: true

  tasks:
    - name: Mise à jour du cache et install haproxy avec la dernière version
      apt:
        name: haproxy
        update_cache: true
        cache_valid_time: 3600

    - name: Désinstallation du package "haproxy"
      apt:
        name: haproxy
        state: absent
        purge: true
        autoremove: true
